version: '3'

services:
  php:
    container_name: ucv-api
    image: ufis/docker-spa-api-image
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
